# Generated by Django 3.0 on 2023-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='name',
            new_name='username',
        ),
    ]
