# Generated by Django 3.0 on 2023-02-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_auto_20230206_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='course',
            field=models.CharField(choices=[('Python Full Stack', 'FSD'), ('DEVOPS', 'DEV')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
