# Generated by Django 3.0 on 2023-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_auto_20230220_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='name',
        ),
        migrations.AddField(
            model_name='formdata',
            name='course',
            field=models.CharField(choices=[('Python Full Stack', 'FSD'), ('DEVOPS', 'DEV')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
